package org.example

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        all(uri: "/**",uriExclude: '/atmosphere/**') {
            before = {
				println "IN Filter controllerName:> "+controllerName
				println "IN Filter actionName:> "+actionName
                // Ignore direct views (e.g. the default main index page).
                if (controllerName?.equals('assets')) return true
				
				if (controllerName?.toString()?.contains(('atmosphere'))) return true
				

                // Access control by convention.
                accessControl()
            }
        }
    }
}
